#!/bin/sh
#
# Store the package we are to download
#
PACKAGE=$1

cd $HOME
#
# Download relevant files
#
TARBALL=$(npm pack "$PACKAGE@*" -g)

#
# Untar the package and install dependencies
#
rm -rf package
tar -zxvf $TARBALL
mv package $HOME/$PACKAGE
cd "$HOME/$PACKAGE"

npm install --production

git init
git add .
git commit -m 'Initial commit' --author="Quill <info@nodejitsu.com>"
